dist: bionic
language: python
python:
  - "3.7"
install:
  - python3 -m pip install --upgrade pip
  - pip install poetry
  - poetry install
script:
  - poetry run coverage run -m pytest
  - poetry run coverage report
  - poetry run coverage xml
after_success:
  - poetry run codecov
